list_1=[]
print('1st Insert India')
list_1.append('India')
print('2nd Insert Pakistan')
list_1.append('Pakistan')
print('3rd Insert Afganistan')
list_1.append('Afganistan')
print('4th Insert China')
list_1.append('China')
print('5th Insert Srilanka')
list_1.append('Srilanka')
print('6th Insert Nepal')
list_1.append('Nepal')

print(list_1)

list_1.pop()
print('1st Pop',list_1)
list_1.pop()
print('2nd Pop',list_1)
list_1.pop()
print('3rd Pop',list_1)
list_1.pop()
print('4th Pop',list_1)
list_1.pop()
print('5th Pop',list_1)
list_1.pop()
print('6th Pop',list_1)
